# Generated by Django 4.0.3 on 2022-03-17 08:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Carrera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreCarrera', models.CharField(max_length=90)),
            ],
        ),
        migrations.CreateModel(
            name='CriterioMatricula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipoColegio', models.BooleanField()),
                ('valorPension', models.IntegerField()),
                ('anioGrado', models.IntegerField(max_length=4)),
                ('estrato', models.IntegerField(max_length=1)),
                ('ingresosAnuales', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Puntaje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('puntajeCN', models.IntegerField(max_length=3)),
                ('puntajeLC', models.IntegerField(max_length=3)),
                ('puntajeMA', models.IntegerField(max_length=3)),
                ('puntajeSC', models.IntegerField(max_length=3)),
                ('puntajeIN', models.IntegerField(max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='SalarioMinimo',
            fields=[
                ('anio', models.IntegerField(max_length=4, primary_key=True, serialize=False)),
                ('valor', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='PuntajePonderado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('puntajePond', models.FloatField()),
                ('puntaje_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='siu.puntaje')),
            ],
        ),
        migrations.CreateModel(
            name='PuntajeCorte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('puntajeMinimo', models.FloatField()),
                ('anio', models.IntegerField(max_length=4)),
                ('periodo', models.IntegerField(max_length=1)),
                ('carrera_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='siu.carrera')),
            ],
        ),
        migrations.CreateModel(
            name='CriterioAdmision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('procentaje', models.FloatField()),
                ('carrera_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='siu.carrera')),
            ],
        ),
        migrations.CreateModel(
            name='Aspirante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_consulta', models.DateField()),
                ('criterio_matricula_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='siu.criteriomatricula')),
                ('puntaje_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='siu.puntaje')),
            ],
        ),
    ]
