# Generated by Django 4.0.3 on 2022-03-17 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siu', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='criterioadmision',
            old_name='procentaje',
            new_name='procentajeCN',
        ),
        migrations.AddField(
            model_name='criterioadmision',
            name='procentajeIN',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='criterioadmision',
            name='procentajeLC',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='criterioadmision',
            name='procentajeMA',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='criterioadmision',
            name='procentajeSC',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
