# Generated by Django 4.0.3 on 2022-03-17 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siu', '0003_alter_puntajecorte_anio_alter_puntajecorte_periodo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='criteriomatricula',
            name='anioGrado',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='criteriomatricula',
            name='estrato',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='puntaje',
            name='puntajeCN',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='puntaje',
            name='puntajeIN',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='puntaje',
            name='puntajeLC',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='puntaje',
            name='puntajeMA',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='puntaje',
            name='puntajeSC',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='salariominimo',
            name='anio',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
